parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    controllers:
        namespace: App\UserInterface\Controller\
        resource: '../src/UserInterface/Controller/'
        tags: [ 'controller.service_arguments' ]
