parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $host: '%env(HOST_API)%'


    #### APPLICATION ####

    use_cases:
        namespace: App\Core\Application\UseCase\
        resource: '../src/Core/Application/UseCase/**/*UseCase*.php'

    gateway_ports:
        namespace: App\Core\Application\Port\Gateway\
        resource: '../src/Core/Application/Port/Gateway/*Interface.php'


    #### INFRASTRUCTURE ####

    gateway_adapters:
        namespace: App\Infrastructure\Gateway\
        resource: '../src/Infrastructure/Gateway/*.php'

    gateway_collectors:
        namespace: App\Infrastructure\DataCollector\
        resource: '../src/Infrastructure/DataCollector/*.php'

    gateway_services:
        namespace: App\Infrastructure\Service\
        resource: '../src/Infrastructure/Service/*.php'

    #### USER INTERFACE ####

    views:
        namespace: App\UserInterface\Presentation\
        resource: '../src/UserInterface/Presentation/**/*View.php'

    presenters:
        namespace: App\UserInterface\Presentation\
        resource: '../src/UserInterface/Presentation/**/*Presenter.php'

    controllers:
        namespace: App\UserInterface\Controller\
        resource: '../src/UserInterface/Controller/*Controller.php'
        tags: ['controller.service_arguments', 'container.service_subscriber']
        public: true
        calls:
            -   method: setContainer
                arguments: ['@Psr\Container\ContainerInterface']
